FROM registry.altlinux.org/alt/alt:p11


ENV PYTHONUNBUFFERED=1


WORKDIR /app


RUN apt-get update && \
    apt-get install -y \
    git \
    python3 \
    python3-module-click \
    python3-module-requests \
    python3-module-tabulate\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/Tor344/alt-branch-matching.git .

ENTRYPOINT ["python3", "-m", "cli.main"]

